[package]
name = "cursive_ideas"
version = "0.1.0"
authors = ["luke <luke@yorkbay.net.nz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.20.0"
rand = "0.8.0"
